site_name: PHS Tech Booth
site_url: https://phs-tech-booth.pages.dev/
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: custom
  logo: assets/PHS.png
  favicon: assets/PHS.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
extra_css:
  - stylesheets/extra.css
plugins:
    - search
    - encryptcontent:
        #password_file: 'passwords.yml'
        global_password: 'password'
        password_button: True
        search_index: 'dynamically'
        title_prefix: ''
        summary: ''
        remember_password: true
        remember_keys: true
